services:

  app-payment:
    build: ./app
    ports:
      - "5002:5002"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_SERVICE_NAME=payment
      - SERVICE_PORT=5002
      - CONFIG_FILE=/app/config.json
    depends_on:
      - tempo
    networks:
      - otel-net
  
  service-a:
    build: ./service-a
    ports:
      - "5000:5000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_SERVICE_NAME=service-a
      # - OTEL_TRACES_EXPORTER=otlp
      # - OTEL_METRICS_EXPORTER=otlp
    depends_on:
      - service-b
      - tempo
    networks:
      - otel-net
    extra_hosts:
      - "nginx-gateway:10.1.1.5"

  service-b:
    build: ./service-b
    ports:
      - "5001:5001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_SERVICE_NAME=service-b
      # - OTEL_TRACES_EXPORTER=otlp
      # - OTEL_METRICS_EXPORTER=otlp
    depends_on:
      - tempo
    networks:
      - otel-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - otel-net
    depends_on:
      - tempo
      - jaeger

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"  # Tempo HTTP API
      # - "4317:4317"  # OTLP gRPC - only for docker network
      # - "4318:4318"  # OTLP HTTP - only for docker network
    networks:
      - otel-net
    depends_on:
      - prometheus
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - otel-net
    depends_on:
      - tempo
      - prometheus

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yml
        - prometheus-data:/prometheus
      ports:
        - "9090:9090"
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--storage.tsdb.retention.time=200h'
        - '--web.enable-lifecycle'
        - '--web.enable-remote-write-receiver'
        - '--enable-feature=native-histograms'
      restart: unless-stopped
      networks:
        - otel-net

  jaeger:
      image: jaegertracing/all-in-one:latest
      container_name: jaeger
      ports:
        - "16686:16686"
        # - "4317:4317"  # OTLP gRPC - only for docker network
        # - "4318:4318"  # OTLP HTTP - only for docker network
      environment:
        - COLLECTOR_OTLP_ENABLED=true
      networks:
        - otel-net

volumes:
  prometheus-data:

networks:
  otel-net:
    driver: bridge
