services:
  service-a:
    build: ./service-a
    ports:
      - "5000:5000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_SERVICE_NAME=service-a
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
    depends_on:
      - service-b
      - otel-collector
    networks:
      - otel-net
    extra_hosts:
      - "nginx-gateway:10.1.1.5"

  service-b:
    build: ./service-b
    ports:
      - "5001:5001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_SERVICE_NAME=service-b
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
    depends_on:
      - otel-collector
    networks:
      - otel-net

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"  # Tempo HTTP API
      - "4317:4317"  # OTLP gRPC (for NGINX/services)
      - "4318:4318"  # OTLP HTTP
      - "9411:9411"  # Zipkin (optional)
    networks:
      - otel-net
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - tempo
    networks:
      - otel-net

networks:
  otel-net:
    driver: bridge
