services:
  service-a:
    build: ./service-a
    ports:
      - "5000:5000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317  # HTTP for simplicity in Python
      - OTEL_SERVICE_NAME=service-a
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
    depends_on:
      - service-b
      - otel-collector
    networks:
      - otel-net
    extra_hosts:
      - "nginx-gateway:10.1.1.5"

  service-b:
    build: ./service-b
    ports:
      - "5001:5001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=service-b
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
    depends_on:
      - otel-collector
    networks:
      - otel-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.109.0
    command: [--config=/etc/otel-collector-config.yml]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"  # OTLP HTTP
      - "4318:4318"  # OTLP gRPC
      - "8888:8888"  # Prometheus metrics (optional)
      - "16686:16686"  # Jaeger v2 UI
      - "14268:14268"
    networks:
      - otel-net

