receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:  # For debugging
    loglevel: debug
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]  # Add Prometheus if needed
