services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./collector/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - otel-net
    depends_on:
      - tempo
      - jaeger

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200"  # Tempo HTTP API
      # - "4317:4317"  # OTLP gRPC - only for docker network
      # - "4318:4318"  # OTLP HTTP - only for docker network
    networks:
      - otel-net
    depends_on:
      - prometheus
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - otel-net
    depends_on:
      - tempo
      - prometheus

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
        - prometheus-data:/prometheus
      ports:
        - "9090:9090"
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--storage.tsdb.retention.time=200h'
        - '--web.enable-lifecycle'
        - '--web.enable-remote-write-receiver'
        - '--enable-feature=native-histograms'
      restart: unless-stopped
      networks:
        - otel-net

  jaeger:
      image: jaegertracing/all-in-one:latest
      container_name: jaeger
      ports:
        - "16686:16686"
        # - "4317:4317"  # OTLP gRPC - only for docker network
        # - "4318:4318"  # OTLP HTTP - only for docker network
      environment:
        - COLLECTOR_OTLP_ENABLED=true
        
      networks:
        - otel-net

  locust:
      image: locustio/locust:latest
      container_name: locust
      ports:
        - "8089:8089"
      volumes:
        - ./locust/locustfile.py:/mnt/locust/locustfile.py
        - ./locust/start-locust.sh:/mnt/locust/start-locust.sh
      entrypoint: ["/mnt/locust/start-locust.sh"]
      environment:
        - LOCUST_HOST=http://${NGINX_GATEWAY_IP_PORT}
      networks:
        - otel-net

volumes:
  prometheus-data: {}
  tempo-data: {}

networks:
  otel-net:
    driver: bridge
