{
 "title": "NGINX-Basics",
 "description": "Dashboard for NGINX Otel Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(nginxplus_nginx_config_uptime,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_http_requests_total[1h]))"
    }
   ]
  },
  {
   "title": "Total (2XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"2xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total (4XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"4xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total (5XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"5xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total requests (rate over 5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "requests (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginxplus_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum (irate(nginxplus_http_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "upstream_server_response_time (avg)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (upstream) (nginxplus_upstream_server_response_time) <= 500",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginxplus_connections_accepted{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "sum(irate(nginxplus_connections_accepted[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginxplus_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(nginxplus_connections_active)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "2XX status code (rate over 5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"2xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "4XX status code (rate over 5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"4xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "5XX status code (rate over 5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"5xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  }
 ]
}