{
 "title": "NGINX-Otel-Demo",
 "description": "Grafana Dashboard for NGINX OpenTelemetry Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(nginxplus_nginx_config_uptime,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Geomap",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{span.client.geo.country.name != \"\" && span.client.geo.lat != \"\" && span.client.geo.lon != \"\"}",
     "tableType": "spans"
    }
   ]
  },
  { "title": "OpenTelemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "limit": 100, "metricsQueryType": "range", "tableType": "traces" }
   ]
  },
  {
   "title": "Service Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "limit": 50, "metricsQueryType": "range", "tableType": "traces" }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Total requests (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginxplus_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum (irate(nginxplus_http_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_http_requests_total[1h]))"
    }
   ]
  },
  {
   "title": "Total (2XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"2xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total (4XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"4xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total (5XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"5xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "upstream_server_response_time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (upstream) (nginxplus_upstream_server_response_time) <= 500",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "Processed connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginxplus_connections_accepted{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "sum(irate(nginxplus_connections_accepted[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginxplus_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(nginxplus_connections_active)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "2XX status code (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"2xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "4XX status code (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"4xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "5XX status code (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"5xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  }
 ]
}